Description: Daily poller for NYT data

Parameters:
    APIKey:
        Type: String
        Description: Developer API Key

    S3Bucket:
        Type: String
        Description: Name of S3 bucket

Resources:

    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: "lambda.amazonaws.com"
                      Action: "sts:AssumeRole"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            Policies:
                - PolicyName: inline-policy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action: "s3:PutObject"
                            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

