Description: Daily poller for NYT data

Parameters:
    APIKey:
        Type: String
        Description: Developer API Key

    S3Bucket:
        Type: String
        Description: Name of S3 bucket

Resources:

    ArticleSearchFunctionExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: "lambda.amazonaws.com"
                      Action: "sts:AssumeRole"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            Policies:
                - PolicyName: inline-policy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action: "s3:PutObject"
                            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
    
    ArticleSearchFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code: ./src
            Environment:
                Variables:
                    API_KEY: !Ref APIKey
                    S3_BUCKET: !Ref S3Bucket
            Handler: "lambda_function.lambda_handler"
            MemorySize: 128
            Role: !GetAtt ArticleSearchFunctionExecutionRole.Arn
            Runtime: python3.8
            Timeout: 75

    ArticleSearchFunctionEventPermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !GetAtt ArticleSearchFunction.Arn
            Principal: "events.amazonaws.com"
            Action: "lambda:InvokeFunction"
            SourceArn: !GetAtt DailyScheduledEventRule.Arn

    DailyScheduledEventRule:
        Type: AWS::Events::Rule
        Properties:
            Description: Kicks off article-searcher once per day
            State: ENABLED
            ScheduleExpression: "cron(30 23 * * ? *)"
            Targets:
                - Arn: !GetAtt ArticleSearchFunction.Arn
                  Id: article-search-function
